# dotdrop config
config:
  backup: true
  compare_workdir: true
  check_version: true
  create: true
  dotpath: "."
  keepdot: true
  link_dotfile_default: link
  longkey: true
  showdiff: true

# prefixes
#   f: file
#   d: directory
dotfiles:
  fProfile:
    src: .profile
    dst: ~/.profile

  # bash
  fBashAliases:
    src: .bash_aliases
    dst: ~/.bash_aliases
  fBashLogout:
    src: .bash_logout
    dst: ~/.bash_logout
  fBashrc:
    src: .bashrc
    dst: ~/.bashrc

  # emacs
  fEmacs:
    src: .emacs
    dst: ~/.emacs

  # fish
  dFish:
    src: .config/fish
    dst: ~/.config/fish

  # git
  fGitconfig:
    src: .gitconfig
    dst: ~/.gitconfig

  # lazygit
  dLazygitConfig:
    src: .config/lazygit/config.yml
    dst: ~/.config/lazygit/config.yml

  # nano
  fNanorc:
    src: .nanorc
    dst: ~/.nanorc
  dNano:
    src: .nano
    dst: ~/.nano

  # starship
  fStarshipTOML:
    src: .config/starship.toml
    dst: ~/.config/starship.toml

  # zsh
  fZshrc:
    src: .zshrc
    dst: ~/.zshrc
  dOhMyZshCustom:
    src: .oh-my-zsh/custom
    dst: ~/.oh-my-zsh/custom

profiles:
  # default profile
  PC:
    dotfiles:
      - fProfile
      # bash
      - fBashAliases
      - fBashLogout
      - fBashrc
      # emacs
      - fEmacs
      # fish
      - dFish
      # git
      - fGitconfig
      # lazygit
      - dLazygitConfig
      # nano
      - fNanorc
      - dNano
      # starship
      - fStarshipTOML
      # zsh
      - fZshrc
      - dOhMyZshCustom
